services:
  - type: web
    name: telegram-status-bot
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
